package com.osmig.Jweb.framework.js;

import jweb.Func;
import jweb.Val;
import jweb.js.Stmt;

/**
 * The ten browser-API modules an app reaches for most, re-exported so that
 * {@code import static jweb.Js.*} covers them — clipboard, observers, storage,
 * history, URLs, form data, animation, media and IndexedDB. Each still has its
 * own import ({@code import static jweb.js.JSStorage.*}) and is the place to
 * read about what it does; this class only forwards.
 *
 * <p>A handful of names stay module-only, because re-exporting them here would
 * silently capture a call that means something else: {@code get}, {@code
 * delete}, {@code pushState}, {@code onPopState} and {@code eventKey} already
 * mean something in the Actions layer; {@code animate}, {@code currentTime},
 * {@code currentUrl}, {@code disconnect}, {@code getQueryParam}, {@code pause},
 * {@code play}, {@code playbackRate}, {@code setCurrentTime}, {@code
 * setPlaybackRate} and {@code toObject} are declared by two of the ten; and
 * {@code audio}, {@code video}, {@code src}, {@code href}, {@code url}, {@code
 * search}, {@code duration}, {@code onAnimationEnd}, {@code onCancel} and
 * {@code onTransitionEnd} would shadow an HTML or CSS name under the
 * four-wildcard import. Import the module for those.</p>
 *
 * <p>Generated by hand once and kept honest by {@code JsModuleFacadeTest},
 * which fails when a module grows a static this class does not forward.</p>
 *
 * @deprecated Replaced by {@code jweb.Js} — shorter import, same API. Existing code keeps working.
 */
@Deprecated
@SuppressWarnings("deprecation")
public class Modules extends Behaviors {

    protected Modules() {}

    /**
     * The names deliberately left off this facade — see the class javadoc.
     * {@code JsModuleFacadeTest} reads it, so the list and the code cannot drift.
     */
    static final java.util.Set<String> MODULE_ONLY = java.util.Set.of(
        "get", "delete", "pushState", "onPopState", "eventKey",
        "animate", "currentTime", "currentUrl", "disconnect", "getQueryParam",
        "pause", "play", "playbackRate", "setCurrentTime", "setPlaybackRate", "toObject",
        "audio", "video", "src", "href", "url", "search", "duration",
        "onAnimationEnd", "onCancel", "onTransitionEnd");

    /** The modules this facade forwards. */
    static final java.util.List<Class<?>> FORWARDED = java.util.List.of(
        JSClipboard.class, JSObservers.class, JSStorage.class, JSHistory.class,
        JSUrl.class, JSFormData.class, JSAnimation.class, JSWebAnimations.class,
        JSMedia.class, JSIndexedDB.class);

    // ==================== JSClipboard — clipboard read/write, with the execCommand fallback ====================

    public static JSClipboard.ClipboardPromise writeText(Val text) { return JSClipboard.writeText(text); }
    public static JSClipboard.ClipboardPromise writeText(String text) { return JSClipboard.writeText(text); }
    public static JSClipboard.ClipboardPromise copyText(String text) { return JSClipboard.copyText(text); }
    public static JSClipboard.ClipboardPromise copyElementText(String elementId) { return JSClipboard.copyElementText(elementId); }
    public static JSClipboard.ClipboardPromise copyElementValue(String elementId) { return JSClipboard.copyElementValue(elementId); }
    public static JSClipboard.ClipboardPromise write(Val clipboardItems) { return JSClipboard.write(clipboardItems); }
    public static JSClipboard.ClipboardPromise readText() { return JSClipboard.readText(); }
    public static JSClipboard.ClipboardPromise read() { return JSClipboard.read(); }
    public static Val clipboardItem(String mimeType, Val blob) { return JSClipboard.clipboardItem(mimeType, blob); }
    public static Val copyFallback(Val text) { return JSClipboard.copyFallback(text); }
    public static Val copyWithFallback(Val text) { return JSClipboard.copyWithFallback(text); }
    public static Val canRead() { return JSClipboard.canRead(); }
    public static Val canWrite() { return JSClipboard.canWrite(); }

    // ==================== JSObservers — Intersection, Mutation and Resize observers ====================

    public static JSObservers.IntersectionBuilder intersection() { return JSObservers.intersection(); }
    public static JSObservers.MutationBuilder mutation() { return JSObservers.mutation(); }
    public static JSObservers.ResizeBuilder resize() { return JSObservers.resize(); }
    public static Val unobserve(String observerVar, Val element) { return JSObservers.unobserve(observerVar, element); }

    // ==================== JSStorage — localStorage, sessionStorage and cookies ====================

    public static JSStorage.Storage local() { return JSStorage.local(); }
    public static JSStorage.Storage session() { return JSStorage.session(); }
    public static Val getCookie(String name) { return JSStorage.getCookie(name); }
    public static Val setCookie(String name, String value, int days) { return JSStorage.setCookie(name, value, days); }
    public static Val setCookie(String name, Val value, int days) { return JSStorage.setCookie(name, value, days); }
    public static Val deleteCookie(String name) { return JSStorage.deleteCookie(name); }
    public static JSStorage.CookieBuilder cookie(String name) { return JSStorage.cookie(name); }
    public static Val onStorageChange(Func handler) { return JSStorage.onStorageChange(handler); }
    public static Val onStorageChange(String code) { return JSStorage.onStorageChange(code); }
    public static Val onStorageKeyChange(String key, Func handler) { return JSStorage.onStorageKeyChange(key, handler); }
    public static Val eventOldValue(Val event) { return JSStorage.eventOldValue(event); }
    public static Val eventNewValue(Val event) { return JSStorage.eventNewValue(event); }
    public static Val eventStorageArea(Val event) { return JSStorage.eventStorageArea(event); }
    public static Val eventUrl(Val event) { return JSStorage.eventUrl(event); }
    public static Val forEachKey(String storageType, Func callback) { return JSStorage.forEachKey(storageType, callback); }
    public static Val getAllKeys(String storageType) { return JSStorage.getAllKeys(storageType); }
    public static Val estimateQuota() { return JSStorage.estimateQuota(); }
    public static Val isPersisted() { return JSStorage.isPersisted(); }
    public static Val requestPersist() { return JSStorage.requestPersist(); }

    // ==================== JSHistory — pushState/replaceState, popstate, query params ====================

    public static Val back() { return JSHistory.back(); }
    public static Val forward() { return JSHistory.forward(); }
    public static Val go(int delta) { return JSHistory.go(delta); }
    public static Val historyLength() { return JSHistory.historyLength(); }
    public static Val historyState() { return JSHistory.historyState(); }
    public static Val scrollRestoration() { return JSHistory.scrollRestoration(); }
    public static Val setScrollRestoration(String mode) { return JSHistory.setScrollRestoration(mode); }
    public static Val replaceState(String url) { return JSHistory.replaceState(url); }
    public static Val replaceState(Val state, String url) { return JSHistory.replaceState(state, url); }
    public static Val replaceState(Val state, Val url) { return JSHistory.replaceState(state, url); }
    public static Val onHashChange(Func handler) { return JSHistory.onHashChange(handler); }
    public static Val offPopState(Val handler) { return JSHistory.offPopState(handler); }
    public static Val offHashChange(Val handler) { return JSHistory.offHashChange(handler); }
    public static Val navigationGuard(Func handler) { return JSHistory.navigationGuard(handler); }
    public static Val navigationGuard(String message) { return JSHistory.navigationGuard(message); }
    public static Val navigationGuardWhen(Val condition, String message) { return JSHistory.navigationGuardWhen(condition, message); }
    public static Val currentHash() { return JSHistory.currentHash(); }
    public static Val setHash(String hash) { return JSHistory.setHash(hash); }
    public static Val setHash(Val hash) { return JSHistory.setHash(hash); }
    public static Val currentPath() { return JSHistory.currentPath(); }
    public static Val currentOrigin() { return JSHistory.currentOrigin(); }
    public static Val currentSearch() { return JSHistory.currentSearch(); }
    public static Val getQueryParams(String name) { return JSHistory.getQueryParams(name); }
    public static Val hasQueryParam(String name) { return JSHistory.hasQueryParam(name); }
    public static Val setQueryParam(String name, String value) { return JSHistory.setQueryParam(name, value); }
    public static Val setQueryParam(String name, Val value) { return JSHistory.setQueryParam(name, value); }
    public static Val removeQueryParam(String name) { return JSHistory.removeQueryParam(name); }
    public static Val queryParamsObject() { return JSHistory.queryParamsObject(); }

    // ==================== JSUrl — URL and URLSearchParams parsing and building ====================

    public static Val currentUrlObject() { return JSUrl.currentUrlObject(); }
    public static Val origin() { return JSUrl.origin(); }
    public static Val protocol(Val url) { return JSUrl.protocol(url); }
    public static Val host(Val url) { return JSUrl.host(url); }
    public static Val hostname(Val url) { return JSUrl.hostname(url); }
    public static Val port(Val url) { return JSUrl.port(url); }
    public static Val pathname(Val url) { return JSUrl.pathname(url); }
    public static Val hash(Val url) { return JSUrl.hash(url); }
    public static Val searchParams(Val url) { return JSUrl.searchParams(url); }
    public static Val params(String queryString) { return JSUrl.params(queryString); }
    public static Val params(Val queryExpr) { return JSUrl.params(queryExpr); }
    public static Val params() { return JSUrl.params(); }
    public static Val getParam(Val params, String name) { return JSUrl.getParam(params, name); }
    public static Val getAllParams(Val params, String name) { return JSUrl.getAllParams(params, name); }
    public static Val hasParam(Val params, String name) { return JSUrl.hasParam(params, name); }
    public static Val setParam(Val params, String name, Val value) { return JSUrl.setParam(params, name, value); }
    public static Val appendParam(Val params, String name, Val value) { return JSUrl.appendParam(params, name, value); }
    public static Val deleteParam(Val params, String name) { return JSUrl.deleteParam(params, name); }
    public static Val paramsToString(Val params) { return JSUrl.paramsToString(params); }
    public static JSUrl.UrlBuilder urlBuilder(String basePath) { return JSUrl.urlBuilder(basePath); }
    public static Val encode(Val value) { return JSUrl.encode(value); }
    public static Val decode(Val value) { return JSUrl.decode(value); }

    // ==================== JSFormData — FormData construction and conversion ====================

    public static Val formData(Val formElement) { return JSFormData.formData(formElement); }
    public static Val formData() { return JSFormData.formData(); }
    public static JSFormData.FormDataBuilder formDataBuilder() { return JSFormData.formDataBuilder(); }
    public static Val append(Val fd, String name, Val value) { return JSFormData.append(fd, name, value); }
    public static Val set(Val fd, String name, Val value) { return JSFormData.set(fd, name, value); }
    public static Val getAll(Val fd, String name) { return JSFormData.getAll(fd, name); }
    public static Val has(Val fd, String name) { return JSFormData.has(fd, name); }
    public static Val toUrlEncoded(Val fd) { return JSFormData.toUrlEncoded(fd); }

    // ==================== JSAnimation — requestAnimationFrame loops, transitions, easing ====================

    public static Val raf(Func callback) { return JSAnimation.raf(callback); }
    public static Val cancelRaf(Val id) { return JSAnimation.cancelRaf(id); }
    public static Val cancelRaf(String varName) { return JSAnimation.cancelRaf(varName); }
    public static JSAnimation.AnimationLoop animationLoop(String fnName) { return JSAnimation.animationLoop(fnName); }
    public static Val transition(Val elem, String property, String from, String to, int durationMs) { return JSAnimation.transition(elem, property, from, to, durationMs); }
    public static Val transition(Val elem, String property, String from, String to, int durationMs, String easing) { return JSAnimation.transition(elem, property, from, to, durationMs, easing); }
    public static Val lerp(Val a, Val b, Val t) { return JSAnimation.lerp(a, b, t); }
    public static Val easeInOutQuad(Val t) { return JSAnimation.easeInOutQuad(t); }

    // ==================== JSWebAnimations — element.animate() and playback control ====================

    public static Val reverse(Val animation) { return JSWebAnimations.reverse(animation); }
    public static Val cancel(Val animation) { return JSWebAnimations.cancel(animation); }
    public static Val finish(Val animation) { return JSWebAnimations.finish(animation); }
    public static Val commitStyles(Val animation) { return JSWebAnimations.commitStyles(animation); }
    public static Val persist(Val animation) { return JSWebAnimations.persist(animation); }
    public static Val playState(Val animation) { return JSWebAnimations.playState(animation); }
    public static Val finished(Val animation) { return JSWebAnimations.finished(animation); }
    public static Val ready(Val animation) { return JSWebAnimations.ready(animation); }
    public static Val onFinish(Val animation, Func handler) { return JSWebAnimations.onFinish(animation, handler); }
    public static Val onRemove(Val animation, Func handler) { return JSWebAnimations.onRemove(animation, handler); }
    public static Val getAnimations(Val element) { return JSWebAnimations.getAnimations(element); }
    public static Val getAllAnimations() { return JSWebAnimations.getAllAnimations(); }
    public static Val performanceNow() { return JSWebAnimations.performanceNow(); }
    public static JSWebAnimations.KeyframeBuilder keyframe() { return JSWebAnimations.keyframe(); }
    public static JSWebAnimations.KeyframeBuilder keyframe(double offset) { return JSWebAnimations.keyframe(offset); }

    // ==================== JSMedia — audio/video control, MediaRecorder, Web Audio ====================

    public static Val load(Val media) { return JSMedia.load(media); }
    public static Val canPlayType(Val media, String mimeType) { return JSMedia.canPlayType(media, mimeType); }
    public static Val volume(Val media) { return JSMedia.volume(media); }
    public static Val volume(Val media, double vol) { return JSMedia.volume(media, vol); }
    public static Val volume(Val media, Val vol) { return JSMedia.volume(media, vol); }
    public static Val muted(Val media) { return JSMedia.muted(media); }
    public static Val muted(Val media, boolean muted) { return JSMedia.muted(media, muted); }
    public static Val muted(Val media, Val muted) { return JSMedia.muted(media, muted); }
    public static Val paused(Val media) { return JSMedia.paused(media); }
    public static Val ended(Val media) { return JSMedia.ended(media); }
    public static Val seeking(Val media) { return JSMedia.seeking(media); }
    public static Val readyState(Val media) { return JSMedia.readyState(media); }
    public static Val currentSrc(Val media) { return JSMedia.currentSrc(media); }
    public static Val loop(Val media) { return JSMedia.loop(media); }
    public static Val loop(Val media, boolean loop) { return JSMedia.loop(media, loop); }
    public static Val autoplay(Val media) { return JSMedia.autoplay(media); }
    public static Val autoplay(Val media, boolean autoplay) { return JSMedia.autoplay(media, autoplay); }
    public static Val controls(Val media) { return JSMedia.controls(media); }
    public static Val controls(Val media, boolean controls) { return JSMedia.controls(media, controls); }
    public static Val buffered(Val media) { return JSMedia.buffered(media); }
    public static Val seekable(Val media) { return JSMedia.seekable(media); }
    public static Val played(Val media) { return JSMedia.played(media); }
    public static Val rangesLength(Val ranges) { return JSMedia.rangesLength(ranges); }
    public static Val rangeStart(Val ranges, int index) { return JSMedia.rangeStart(ranges, index); }
    public static Val rangeEnd(Val ranges, int index) { return JSMedia.rangeEnd(ranges, index); }
    public static JSMedia.MediaRecorderBuilder mediaRecorder(Val stream) { return JSMedia.mediaRecorder(stream); }
    public static Val startRecording(Val recorder) { return JSMedia.startRecording(recorder); }
    public static Val startRecording(Val recorder, int timeslice) { return JSMedia.startRecording(recorder, timeslice); }
    public static Val stopRecording(Val recorder) { return JSMedia.stopRecording(recorder); }
    public static Val pauseRecording(Val recorder) { return JSMedia.pauseRecording(recorder); }
    public static Val resumeRecording(Val recorder) { return JSMedia.resumeRecording(recorder); }
    public static Val requestData(Val recorder) { return JSMedia.requestData(recorder); }
    public static Val recorderState(Val recorder) { return JSMedia.recorderState(recorder); }
    public static Val isTypeSupported(String mimeType) { return JSMedia.isTypeSupported(mimeType); }
    public static Val requestPictureInPicture(Val video) { return JSMedia.requestPictureInPicture(video); }
    public static Val exitPictureInPicture() { return JSMedia.exitPictureInPicture(); }
    public static Val pictureInPictureElement() { return JSMedia.pictureInPictureElement(); }
    public static Val pictureInPictureEnabled() { return JSMedia.pictureInPictureEnabled(); }
    public static Val onEnterPiP(Val video, Func handler) { return JSMedia.onEnterPiP(video, handler); }
    public static Val onLeavePiP(Val video, Func handler) { return JSMedia.onLeavePiP(video, handler); }
    public static JSMedia.MediaSessionBuilder mediaSession() { return JSMedia.mediaSession(); }
    public static Val setMediaMetadata(String title, String artist, String album, String artworkUrl) { return JSMedia.setMediaMetadata(title, artist, album, artworkUrl); }
    public static Val setPlaybackState(String state) { return JSMedia.setPlaybackState(state); }
    public static Val setActionHandler(String action, Func handler) { return JSMedia.setActionHandler(action, handler); }
    public static Val audioContext() { return JSMedia.audioContext(); }
    public static Val audioContext(Val options) { return JSMedia.audioContext(options); }
    public static Val destination(Val ctx) { return JSMedia.destination(ctx); }
    public static Val audioContextCurrentTime(Val ctx) { return JSMedia.audioContextCurrentTime(ctx); }
    public static Val audioContextState(Val ctx) { return JSMedia.audioContextState(ctx); }
    public static Val audioState(Val ctx) { return JSMedia.audioState(ctx); }
    public static Val resumeAudioContext(Val ctx) { return JSMedia.resumeAudioContext(ctx); }
    public static Val resume(Val ctx) { return JSMedia.resume(ctx); }
    public static Val suspendAudioContext(Val ctx) { return JSMedia.suspendAudioContext(ctx); }
    public static Val closeAudioContext(Val ctx) { return JSMedia.closeAudioContext(ctx); }
    public static Val createGain(Val ctx) { return JSMedia.createGain(ctx); }
    public static Val createOscillator(Val ctx) { return JSMedia.createOscillator(ctx); }
    public static Val createAnalyser(Val ctx) { return JSMedia.createAnalyser(ctx); }
    public static Val createBiquadFilter(Val ctx) { return JSMedia.createBiquadFilter(ctx); }
    public static Val createDelay(Val ctx) { return JSMedia.createDelay(ctx); }
    public static Val createDelay(Val ctx, double maxDelayTime) { return JSMedia.createDelay(ctx, maxDelayTime); }
    public static Val createBuffer(Val ctx, int channels, int length, int sampleRate) { return JSMedia.createBuffer(ctx, channels, length, sampleRate); }
    public static Val createBufferSource(Val ctx) { return JSMedia.createBufferSource(ctx); }
    public static Val createMediaElementSource(Val ctx, Val mediaElement) { return JSMedia.createMediaElementSource(ctx, mediaElement); }
    public static Val createMediaStreamSource(Val ctx, Val stream) { return JSMedia.createMediaStreamSource(ctx, stream); }
    public static Val connect(Val source, Val destination) { return JSMedia.connect(source, destination); }
    public static Val startOscillator(Val osc) { return JSMedia.startOscillator(osc); }
    public static Val startOscillator(Val osc, double when) { return JSMedia.startOscillator(osc, when); }
    public static Val stopOscillator(Val osc) { return JSMedia.stopOscillator(osc); }
    public static Val stopOscillator(Val osc, double when) { return JSMedia.stopOscillator(osc, when); }
    public static Val gainValue(Val gainNode) { return JSMedia.gainValue(gainNode); }
    public static Val setGainValue(Val gainNode, double value) { return JSMedia.setGainValue(gainNode, value); }
    public static Val setGainValue(Val gainNode, Val value) { return JSMedia.setGainValue(gainNode, value); }
    public static Val frequency(Val osc) { return JSMedia.frequency(osc); }
    public static Val setFrequency(Val osc, double freq) { return JSMedia.setFrequency(osc, freq); }
    public static Val setFrequency(Val osc, Val freq) { return JSMedia.setFrequency(osc, freq); }
    public static Val oscillatorType(Val osc) { return JSMedia.oscillatorType(osc); }
    public static Val setOscillatorType(Val osc, String type) { return JSMedia.setOscillatorType(osc, type); }
    public static Val setValueAtTime(Val param, double value, double time) { return JSMedia.setValueAtTime(param, value, time); }
    public static Val linearRampToValueAtTime(Val param, double value, double time) { return JSMedia.linearRampToValueAtTime(param, value, time); }
    public static Val exponentialRampToValueAtTime(Val param, double value, double time) { return JSMedia.exponentialRampToValueAtTime(param, value, time); }

    // ==================== JSIndexedDB — openDB/createStore/transaction/cursor builders ====================

    public static JSIndexedDB.OpenDBBuilder openDB(String name, int version) { return JSIndexedDB.openDB(name, version); }
    public static JSIndexedDB.OpenDBBuilder openDB(Val name, Val version) { return JSIndexedDB.openDB(name, version); }
    public static Val deleteDB(String name) { return JSIndexedDB.deleteDB(name); }
    public static Val deleteDB(Val name) { return JSIndexedDB.deleteDB(name); }
    public static Val listDatabases() { return JSIndexedDB.listDatabases(); }
    public static JSIndexedDB.CreateStoreBuilder createStore(Val db, String storeName) { return JSIndexedDB.createStore(db, storeName); }
    public static Val deleteStore(Val db, String storeName) { return JSIndexedDB.deleteStore(db, storeName); }
    public static JSIndexedDB.TransactionBuilder transaction(Val db, String storeNames, String mode) { return JSIndexedDB.transaction(db, storeNames, mode); }
    public static JSIndexedDB.TransactionBuilder transaction(Val db, String storeNames) { return JSIndexedDB.transaction(db, storeNames); }
    public static JSIndexedDB.CursorBuilder cursorQuery(Val db, String storeName) { return JSIndexedDB.cursorQuery(db, storeName); }
    public static Val indexGet(Val db, String storeName, String indexName, Val key) { return JSIndexedDB.indexGet(db, storeName, indexName, key); }
    public static Val indexGetAll(Val db, String storeName, String indexName, Val key) { return JSIndexedDB.indexGetAll(db, storeName, indexName, key); }
    public static Val keyOnly(Object value) { return JSIndexedDB.keyOnly(value); }
    public static Val keyLowerBound(Object lower) { return JSIndexedDB.keyLowerBound(lower); }
    public static Val keyLowerBound(Object lower, boolean open) { return JSIndexedDB.keyLowerBound(lower, open); }
    public static Val keyUpperBound(Object upper) { return JSIndexedDB.keyUpperBound(upper); }
    public static Val keyUpperBound(Object upper, boolean open) { return JSIndexedDB.keyUpperBound(upper, open); }
    public static Val keyBound(Object lower, Object upper) { return JSIndexedDB.keyBound(lower, upper); }
    public static Val keyBound(Object lower, Object upper, boolean lowerOpen, boolean upperOpen) { return JSIndexedDB.keyBound(lower, upper, lowerOpen, upperOpen); }
    public static Val promisify(Val request) { return JSIndexedDB.promisify(request); }
    public static Val promisifyTransaction(Val transaction) { return JSIndexedDB.promisifyTransaction(transaction); }
}
